//NO NEED TO USE % FOR CHECKING IF THE NUMBER IS EVEN OR ODD.
if(x & 1)
{
	cout<<"Odd";
}
else
{
	cout<<"Even";
}

//WANT TO DO FAST MULTIPLICATION OF DIVISION WITH 2 ? USE BINARY SHIFTING
x=x<<1;   //MUTIPLY WITH 2
x=x>>1;  //DIVIDE BY 2 

//SWAP NUMBERS USING XOR. THIS METHOD IS MORE EFFICIENT AND ALSO DOES NOT REQUIRE THIRD VARIABLE
x^=y;
y^=x;
x^=y;


//use emplace_back() INSTEAD push_back() BECOZ IT IS MUCH FASTER AND EFFICIENT


//YOU CAN CALCULATE THE MOST SIGNIFICANT DIGIT BY USING THIS
N is a number
double x= log10(N);
x= floor(x);
//SO NOW ,X IS THE MOST SIGNIFICANT DIGIT.


